version: '3'


services:
  app_one:
    build:
      context: .
      dockerfile: dockerfile
    container_name: app_one_c
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"
    networks:
      - app-network
  app_two:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - APP_NAME=App2
    container_name: app_two_c
    ports:
      - "3002:3000"
    networks:
      - app-network
  app_three:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - APP_NAME=App3
    container_name: app_three_c
    ports:
      - "3003:3000"
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./html:/usr/share/nginx/html:ro  
    depends_on:
      - app_one
      - app_two
      - app_three
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    